# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)
#Food.create(:week => '${week}'. :name: => '${1}', :meatiness: => 'unknown')
#perl -ne 'if(!$week) {$week=1}; /^$/ && $week++; s/^(.*)$/Food.create(:week => "${week}", :name => "${1}", :meatiness => "unknown")/; print' </tmp/kiertävä_ruokalista >>ruokalista/db/seeds.rb

Food.create(:week => "1", :name => "kotletit ja mac n'cheese", :meatiness => "unknown")
Food.create(:week => "1", :name => "härkäsalaatti/juustosalaatti", :meatiness => "unknown")
Food.create(:week => "1", :name => "jauhelihakeitto/soijarouhekeitto", :meatiness => "unknown")
Food.create(:week => "1", :name => "uuniperuna kinkku/aurajuusto/lohi/tonnikala/vuohenjuustokastikkeella", :meatiness => "unknown")
Food.create(:week => "1", :name => "fetawrapit", :meatiness => "unknown")
Food.create(:week => "1", :name => "kuskussalaatti tonnikalalla/fetalla", :meatiness => "unknown")
Food.create(:week => "1", :name => "karjalanpaisti tmv. lihakastike uunissa /  soijakastike uunissa, perunoita", :meatiness => "unknown")
Food.create(:week => "1", :name => "lihamureke/soijamureke, valkosipuliperunat", :meatiness => "unknown")
Food.create(:week => "1", :name => "lohimedaljonkeja/tofua ja perunamuusia", :meatiness => "unknown")
Food.create(:week => "2", :name => "", :meatiness => "unknown")
Food.create(:week => "2", :name => "juusto-kasvissuikale-perunakiusaus", :meatiness => "unknown")
Food.create(:week => "2", :name => "broilerinkoipia kasvisriisipedillä/tofua ja eilistä kiusausta", :meatiness => "unknown")
Food.create(:week => "2", :name => "lohikeitto/juusto-kasviskeitto", :meatiness => "unknown")
Food.create(:week => "2", :name => "siskonmakkarakeitto/tofu-kasvis-nuudelikeitto kookoskermalla", :meatiness => "unknown")
Food.create(:week => "2", :name => "täytettyjä kesäkurpitsoita(paprikoita ja perunaa", :meatiness => "unknown")
Food.create(:week => "2", :name => "tomaattipasta", :meatiness => "unknown")
Food.create(:week => "2", :name => "täytettyjä lettuja", :meatiness => "unknown")
Food.create(:week => "2", :name => "juurespihvit perunoilla ja kermaviilikastikkeella", :meatiness => "unknown")
Food.create(:week => "2", :name => "pippuripihvi/lehtipihvi, perunoita, sienikastiketta", :meatiness => "unknown")
Food.create(:week => "3", :name => "", :meatiness => "unknown")
Food.create(:week => "3", :name => "kanapihvejä/tofua ja riisiä", :meatiness => "unknown")
Food.create(:week => "3", :name => "soijakasvislasagne", :meatiness => "unknown")
Food.create(:week => "3", :name => "kalapuikot ja pariisinperunat", :meatiness => "unknown")
Food.create(:week => "3", :name => "tomaattinen jauheliha-minestronekeitto", :meatiness => "unknown")
Food.create(:week => "3", :name => "kananuggetteja/kasvisnuggetteja ja raskalaisia/lohkoperunoita", :meatiness => "unknown")
Food.create(:week => "3", :name => "pinaattilettuja", :meatiness => "unknown")
Food.create(:week => "3", :name => "nakit/soijanakit ja ranskalaiset/ristikkoperunat", :meatiness => "unknown")
Food.create(:week => "3", :name => "tacoja/tortilloja", :meatiness => "unknown")
Food.create(:week => "3", :name => "jauheliha-linssikeitto (osa ilman jauhelihaa)", :meatiness => "unknown")
Food.create(:week => "4", :name => "", :meatiness => "unknown")
Food.create(:week => "4", :name => "jauheliha/kasvispihvit ja perunat", :meatiness => "unknown")
Food.create(:week => "4", :name => "tofu/kananuudeliwok", :meatiness => "unknown")
Food.create(:week => "4", :name => "kasvissosekeitto", :meatiness => "unknown")
Food.create(:week => "4", :name => "uunilohi/paistettua tofua ja perunamuusia", :meatiness => "unknown")
Food.create(:week => "4", :name => "soijamakaronilaatikkoa", :meatiness => "unknown")
Food.create(:week => "4", :name => "lohipasta", :meatiness => "unknown")
Food.create(:week => "4", :name => "meksikolainen salaatti", :meatiness => "unknown")
Food.create(:week => "4", :name => "pizzaa (ötker/kotipizza)", :meatiness => "unknown")
Food.create(:week => "4", :name => "feta-pinaattipiirakka/kinkkupiirakka", :meatiness => "unknown")
Food.create(:week => "5", :name => "", :meatiness => "unknown")
Food.create(:week => "5", :name => "juustosalaatti", :meatiness => "unknown")
Food.create(:week => "5", :name => "pangasius/kuha/ahvenfilettä/tofua ja perunoita, kermaviilikastiketta", :meatiness => "unknown")
Food.create(:week => "5", :name => "makaronia ja jauheliha/soijakastiketta", :meatiness => "unknown")
Food.create(:week => "5", :name => "kiinalainen keitto kasviksilla/kanalla", :meatiness => "unknown")
Food.create(:week => "5", :name => "suppilovahverorisotto", :meatiness => "unknown")
Food.create(:week => "5", :name => "avokadopasta", :meatiness => "unknown")
Food.create(:week => "5", :name => "lihapyörykät/jauhelihapihvit ja perunoita", :meatiness => "unknown")
Food.create(:week => "5", :name => "tonnikalalaatikko/kasvislaatikko", :meatiness => "unknown")
Food.create(:week => "5", :name => "noutokiinalaista/hampparia/subia", :meatiness => "unknown")